services:
  - docker

language: generic

script:
  - ./zazu-softpos/compile.sh

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=oinker/kotoulas-pos-container
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker push $REPO

env:
  global:
    - secure: "DCS3TeHq/3tgJBr0x45opEdZZ9EcCVKz8LxuO4wiIOaTAK71vcQUma9kt/R0xIdCWUZgd4tBRqWy4jk2SEiF7X5GSt4SsVUbOsuaBTjQeqQunh+MYkddmsbGQpYKq05Ax/S3thuHTuQGMcno2kdJIG9V+WWe8eIsXPyXCM8yv6VoazWup8MRPM6DCoLCXWaiGdL8LbzOhS6DZHxF28RjspLhjyCkwSP1UXZ7IdN9ot5M7pUVrwgNLx+YMDOjb4aLKxDJ8gjTNr7WiuaqdZaxGwBqTlXCyW7UJtX5oO3gcjACiSsLus50+o6vE4RYUi9deLtshN4p7rLwVZaA1zjESLtWuFGSe0PoMjNrYdRp1nWs5HLuQMcJ3V0uE8+oH5sKtyYZIeWzhtu0vIryFwsjciviwWuKAJcwK3aO6NGZfE3gUw5MmTs/JOrE4im36wkf5IdJaliD8zqWPuCFOzCjsRVis4Y0c6dQM8sFrya+mj9837Dq4JzEUwVgFUsZud3QsDt34gPkhYPx2cvrkF1+Q3oDsxNyJHggaT5V/9eUBmdTB+GhvzJPkO0z3u4wIuSb7y7mL7JwU838uF7NSs84f05wOY8aSQPFWpjTQtjld8FM9jGSv66sTQ43htLpjwbtQMgxEIwIGpM2ZOkVwB2l4BUx92bzcQYsTii0P2mSGqg=" # DOCKER_EMAIL
    - secure: "mXaUmENe7VG3URGinqmAa1Sl0bF9nxEeZhROtTCvmy1KnlBwY9purq8jBRiwwmEF5aaOFeJtsua015Vj5FQ4JrRzVf5ZXkUvspV43yAK6TlN8QaBEmzRmdlyRe9rZumPdr0rVEBLe1WNt5rgnJybOFoIEBNIJ5LL6MiOrJI4YMe10kHpXd+2je4iOnbRDyLtK/MMffAHL8ydL8fXU3BYUtx6Wh7yjEjXBopW+mhE/cp8ChMwG1fC2R4wQQNnBNIFha9wwa5mOeIhWPb84eqNxvh+pB1SCHtCiJxT/hswwZjXaKOC8FzQOxeYoOjP0nVpIVLrJ+7ZMCaWHB31OjMgVP/AqCBDbapn2d48gR3jf6BDWKu24pqYQmODATBHApKYptcKE6YRh6CIGvZsJFZBMjMEEPcl2iBn8ZTnzDyGTskI1aqGLdtDQZwxXCNXsuNlDY5lsXqSWOmYC01sDpDe1LhZBfA5LAWfSuz4jCLUIOdMpz9JlU3Oxl+mrmBH4SCNd2ZBC0eriWN+fQJeMR/6Fd7e0f7o9EQZ72ccW7wTiT4zRrrAFm20Pk0YBPw/3wlscGp4psyIFKZMKfZk3XpyrGEqiCM3KTn4/vUiv96Ol1nmGdH2RQ9rJyoT7r6MCnqoVO4o7+xkYLXHdS/Q5nW7gHDx2VvrB4Ix6hKBl1C0PJo=" # DOCKER_USER
    - secure: "DlzywYi+00ANkVV4JJeckJownXlesR3K6WgH9g6SoYMleFTdvQ7vO1hiJPQgMwwUzq7vF5TASVs0M7yGM+3Dlgn9GA0HocT6hSwp+D248rLNjY/4JvW9kIW0O+6aPArxtrTSlsh9mSZIRZo7LJA0lV06+uUCGt3mdVDrgYbscPYd5ZKUsFmhprH3PWLvaYfoJrwUrZEExqC/Bq48oMafc/1wL06uSr1lYdZSoLh04tWE0rQMRallMtq6j5rh6YFD09EuMknVosbU18IBARnIEidzZ+TQqezABKxEcObuM7GUpmpv3OxghscKq3AJA/errAsxrjWHinowywFHZFNvnP3iOAdZPc3VtDIifwVdGx8VV0TfyqPHMVtbBoKOX8xslrz3jNHBE55TDI9tnSfqhTLB/rQVLt4YDx5Y28mR8hxUDHupJz4q/lH9ljAPUenHQTNWJaXj0ZP5nk6gvnTXs6GMPZp+r3E+dIVJ7gXj8vS20dA1NVKgoE/RwaOQn1zjFCQMKIj4bVHJurfjcR1k7kI4lbHxql4z+5xhVnGE6ZdIUUT9xIrpjm9OKMSUfvmIXNMLId26RtoYkhTb4PfUsvtZUdmTvVa4mfKkjdxzPs2YuiGHJtqG3ZKbb+OcULD4maJzmGvG+zQpUJSo6iZez3Yn+NDE41uCmC5nz83s0OI=" # DOCKER_PASS
    - COMMIT=${TRAVIS_COMMIT::6}